//
// Generated by Bluespec Compiler, version 2024.01-9-gc481d7f5 (build c481d7f5)
//
// On Mon May 27 18:45:31 CEST 2024
//
//
// Ports:
// Name                         I/O  size props
// reg_rdata_0                    O     8 reg
// reg_rdata_1                    O     8 reg
// reg_rdata_2                    O     8 reg
// reg_rdata_3                    O     8 reg
// reg_status                     O     8 reg
// swclk                          O     1 reg
// swd_out                        O     1 reg
// out_en                         O     1 reg
// CLK                            I     1 clock
// RST_N                          I     1 reset
// address                        I    16 unused
// write_data                     I     8
// write                          I     1
// read                           I     1
// en_rdata_0                     I     1
// en_rdata_1                     I     1
// en_rdata_2                     I     1
// en_rdata_3                     I     1
// en_wdata_0                     I     1
// en_wdata_1                     I     1
// en_wdata_2                     I     1
// en_wdata_3                     I     1
// en_cmd                         I     1
// en_status                      I     1
// swd_in                         I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module swd_module(CLK,
		  RST_N,

		  address,

		  write_data,

		  write,

		  read,

		  en_rdata_0,

		  en_rdata_1,

		  en_rdata_2,

		  en_rdata_3,

		  en_wdata_0,

		  en_wdata_1,

		  en_wdata_2,

		  en_wdata_3,

		  en_cmd,

		  en_status,

		  reg_rdata_0,

		  reg_rdata_1,

		  reg_rdata_2,

		  reg_rdata_3,

		  reg_status,

		  swclk,

		  swd_in,

		  swd_out,

		  out_en);
  input  CLK;
  input  RST_N;

  // action method bus_address
  input  [15 : 0] address;

  // action method bus_write_data
  input  [7 : 0] write_data;

  // action method bus_write
  input  write;

  // action method bus_read
  input  read;

  // action method bus_en_rdata_0
  input  en_rdata_0;

  // action method bus_en_rdata_1
  input  en_rdata_1;

  // action method bus_en_rdata_2
  input  en_rdata_2;

  // action method bus_en_rdata_3
  input  en_rdata_3;

  // action method bus_en_wdata_0
  input  en_wdata_0;

  // action method bus_en_wdata_1
  input  en_wdata_1;

  // action method bus_en_wdata_2
  input  en_wdata_2;

  // action method bus_en_wdata_3
  input  en_wdata_3;

  // action method bus_en_cmd
  input  en_cmd;

  // action method bus_en_status
  input  en_status;

  // value method bus_reg_rdata_0
  output [7 : 0] reg_rdata_0;

  // value method bus_reg_rdata_1
  output [7 : 0] reg_rdata_1;

  // value method bus_reg_rdata_2
  output [7 : 0] reg_rdata_2;

  // value method bus_reg_rdata_3
  output [7 : 0] reg_rdata_3;

  // value method bus_reg_status
  output [7 : 0] reg_status;

  // value method pins_swclk
  output swclk;

  // action method pins_swd_in
  input  swd_in;

  // value method pins_swd_out
  output swd_out;

  // value method pins_out_en
  output out_en;

  // signals for module outputs
  wire [7 : 0] reg_rdata_0, reg_rdata_1, reg_rdata_2, reg_rdata_3, reg_status;
  wire out_en, swclk, swd_out;

  // inlined wires
  wire swd_controller_reset_in$whas;

  // register bus_reg_rdata_0
  reg [7 : 0] bus_reg_rdata_0;
  wire [7 : 0] bus_reg_rdata_0$D_IN;
  wire bus_reg_rdata_0$EN;

  // register bus_reg_rdata_1
  reg [7 : 0] bus_reg_rdata_1;
  wire [7 : 0] bus_reg_rdata_1$D_IN;
  wire bus_reg_rdata_1$EN;

  // register bus_reg_rdata_2
  reg [7 : 0] bus_reg_rdata_2;
  wire [7 : 0] bus_reg_rdata_2$D_IN;
  wire bus_reg_rdata_2$EN;

  // register bus_reg_rdata_3
  reg [7 : 0] bus_reg_rdata_3;
  wire [7 : 0] bus_reg_rdata_3$D_IN;
  wire bus_reg_rdata_3$EN;

  // register bus_reg_status
  reg [7 : 0] bus_reg_status;
  wire [7 : 0] bus_reg_status$D_IN;
  wire bus_reg_status$EN;

  // register cmd
  reg [8 : 0] cmd;
  wire [8 : 0] cmd$D_IN;
  wire cmd$EN;

  // register rdata
  reg [31 : 0] rdata;
  wire [31 : 0] rdata$D_IN;
  wire rdata$EN;

  // register ready
  reg ready;
  wire ready$D_IN, ready$EN;

  // register state
  reg [1 : 0] state;
  wire [1 : 0] state$D_IN;
  wire state$EN;

  // register status
  reg [1 : 0] status;
  wire [1 : 0] status$D_IN;
  wire status$EN;

  // register swd_controller_ack
  reg [2 : 0] swd_controller_ack;
  wire [2 : 0] swd_controller_ack$D_IN;
  wire swd_controller_ack$EN;

  // register swd_controller_cnt
  reg [6 : 0] swd_controller_cnt;
  reg [6 : 0] swd_controller_cnt$D_IN;
  wire swd_controller_cnt$EN;

  // register swd_controller_data
  reg [32 : 0] swd_controller_data;
  reg [32 : 0] swd_controller_data$D_IN;
  wire swd_controller_data$EN;

  // register swd_controller_out_en
  reg swd_controller_out_en;
  wire swd_controller_out_en$D_IN, swd_controller_out_en$EN;

  // register swd_controller_packet
  reg [7 : 0] swd_controller_packet;
  reg [7 : 0] swd_controller_packet$D_IN;
  wire swd_controller_packet$EN;

  // register swd_controller_rnw
  reg swd_controller_rnw;
  wire swd_controller_rnw$D_IN, swd_controller_rnw$EN;

  // register swd_controller_state
  reg [3 : 0] swd_controller_state;
  reg [3 : 0] swd_controller_state$D_IN;
  wire swd_controller_state$EN;

  // register swd_controller_status
  reg [2 : 0] swd_controller_status;
  wire [2 : 0] swd_controller_status$D_IN;
  wire swd_controller_status$EN;

  // register swd_controller_swclk
  reg swd_controller_swclk;
  wire swd_controller_swclk$D_IN, swd_controller_swclk$EN;

  // register swd_controller_swd_out
  reg swd_controller_swd_out;
  reg swd_controller_swd_out$D_IN;
  wire swd_controller_swd_out$EN;

  // register wdata
  reg [31 : 0] wdata;
  reg [31 : 0] wdata$D_IN;
  wire wdata$EN;

  // ports of submodule swd_controller_prescaler_ctr
  wire [5 : 0] swd_controller_prescaler_ctr$DATA_A,
	       swd_controller_prescaler_ctr$DATA_B,
	       swd_controller_prescaler_ctr$DATA_C,
	       swd_controller_prescaler_ctr$DATA_F,
	       swd_controller_prescaler_ctr$Q_OUT;
  wire swd_controller_prescaler_ctr$ADDA,
       swd_controller_prescaler_ctr$ADDB,
       swd_controller_prescaler_ctr$SETC,
       swd_controller_prescaler_ctr$SETF;

  // rule scheduling signals
  wire WILL_FIRE_RL_do_bus_write, WILL_FIRE_RL_do_idle, WILL_FIRE_RL_do_rw;

  // inputs to muxes for submodule ports
  reg [2 : 0] MUX_swd_controller_status$write_1__VAL_1;
  wire [32 : 0] MUX_swd_controller_data$write_1__VAL_1,
		MUX_swd_controller_data$write_1__VAL_2,
		MUX_swd_controller_data$write_1__VAL_3;
  wire [8 : 0] MUX_cmd$write_1__VAL_2;
  wire [7 : 0] MUX_swd_controller_packet$write_1__VAL_1,
	       MUX_swd_controller_packet$write_1__VAL_2;
  wire [6 : 0] MUX_swd_controller_cnt$write_1__VAL_2,
	       MUX_swd_controller_cnt$write_1__VAL_4,
	       MUX_swd_controller_cnt$write_1__VAL_5,
	       MUX_swd_controller_cnt$write_1__VAL_6;
  wire [3 : 0] MUX_swd_controller_state$write_1__VAL_1,
	       MUX_swd_controller_state$write_1__VAL_3,
	       MUX_swd_controller_state$write_1__VAL_7;
  wire [1 : 0] MUX_state$write_1__VAL_2, MUX_status$write_1__VAL_2;
  wire MUX_cmd$write_1__SEL_1,
       MUX_cmd$write_1__SEL_2,
       MUX_swd_controller_cnt$write_1__PSEL_1,
       MUX_swd_controller_cnt$write_1__PSEL_6,
       MUX_swd_controller_cnt$write_1__SEL_1,
       MUX_swd_controller_cnt$write_1__SEL_2,
       MUX_swd_controller_cnt$write_1__SEL_3,
       MUX_swd_controller_cnt$write_1__SEL_4,
       MUX_swd_controller_cnt$write_1__SEL_5,
       MUX_swd_controller_cnt$write_1__SEL_6,
       MUX_swd_controller_data$write_1__SEL_1,
       MUX_swd_controller_data$write_1__SEL_2,
       MUX_swd_controller_data$write_1__SEL_3,
       MUX_swd_controller_packet$write_1__SEL_1,
       MUX_swd_controller_packet$write_1__SEL_2,
       MUX_swd_controller_state$write_1__PSEL_4,
       MUX_swd_controller_state$write_1__SEL_3,
       MUX_swd_controller_state$write_1__SEL_4,
       MUX_swd_controller_state$write_1__SEL_5,
       MUX_swd_controller_state$write_1__SEL_6,
       MUX_swd_controller_status$write_1__SEL_1,
       MUX_swd_controller_swclk$write_1__SEL_1,
       MUX_swd_controller_swclk$write_1__SEL_2,
       MUX_swd_controller_swd_out$write_1__PSEL_4,
       MUX_swd_controller_swd_out$write_1__SEL_3,
       MUX_swd_controller_swd_out$write_1__SEL_4,
       MUX_swd_controller_swd_out$write_1__VAL_3;

  // remaining internal signals
  wire [15 : 0] _0xE79E__q2;
  wire [6 : 0] i__h1352, x__h14830;
  wire [1 : 0] cmd_BITS_4_TO_3__q1;
  wire bus_en_wdata_0_whas__25_AND_bus_en_wdata_0_wge_ETC___d146,
       bus_en_wdata_0_whas__25_AND_bus_en_wdata_0_wge_ETC___d147,
       bus_en_wdata_0_whas__25_AND_bus_en_wdata_0_wge_ETC___d148,
       swd_controller_data_9_BIT_0_3_XOR_swd_controll_ETC___d331,
       x__h1333,
       x__h20797,
       x__h20810,
       z__h24044,
       z__h24051,
       z__h24058,
       z__h24065,
       z__h24072,
       z__h24079,
       z__h24086,
       z__h24093,
       z__h24100,
       z__h24107,
       z__h24114,
       z__h24121,
       z__h24128,
       z__h24135,
       z__h24142,
       z__h24149,
       z__h24156,
       z__h24163,
       z__h24170,
       z__h24177,
       z__h24184,
       z__h24191,
       z__h24198,
       z__h24205,
       z__h24212,
       z__h24219,
       z__h24226,
       z__h24233,
       z__h24240,
       z__h24247,
       z__h34549,
       z__h34556,
       z__h34563,
       z__h34570,
       z__h34577,
       z__h34584,
       z__h34591,
       z__h34598,
       z__h34605,
       z__h34612,
       z__h34619,
       z__h34626,
       z__h34633,
       z__h34640,
       z__h34647,
       z__h34654,
       z__h34661,
       z__h34668,
       z__h34675,
       z__h34682,
       z__h34689,
       z__h34696,
       z__h34703,
       z__h34710,
       z__h34717,
       z__h34724,
       z__h34731,
       z__h34738,
       z__h34745,
       z__h34752,
       z__h34759;

  // value method bus_reg_rdata_0
  assign reg_rdata_0 = bus_reg_rdata_0 ;

  // value method bus_reg_rdata_1
  assign reg_rdata_1 = bus_reg_rdata_1 ;

  // value method bus_reg_rdata_2
  assign reg_rdata_2 = bus_reg_rdata_2 ;

  // value method bus_reg_rdata_3
  assign reg_rdata_3 = bus_reg_rdata_3 ;

  // value method bus_reg_status
  assign reg_status = bus_reg_status ;

  // value method pins_swclk
  assign swclk = swd_controller_swclk ;

  // value method pins_swd_out
  assign swd_out = swd_controller_swd_out ;

  // value method pins_out_en
  assign out_en = swd_controller_out_en ;

  // submodule swd_controller_prescaler_ctr
  Counter #(.width(32'd6),
	    .init(6'd31)) swd_controller_prescaler_ctr(.CLK(CLK),
						       .RST(RST_N),
						       .DATA_A(swd_controller_prescaler_ctr$DATA_A),
						       .DATA_B(swd_controller_prescaler_ctr$DATA_B),
						       .DATA_C(swd_controller_prescaler_ctr$DATA_C),
						       .DATA_F(swd_controller_prescaler_ctr$DATA_F),
						       .ADDA(swd_controller_prescaler_ctr$ADDA),
						       .ADDB(swd_controller_prescaler_ctr$ADDB),
						       .SETC(swd_controller_prescaler_ctr$SETC),
						       .SETF(swd_controller_prescaler_ctr$SETF),
						       .Q_OUT(swd_controller_prescaler_ctr$Q_OUT));

  // rule RL_do_bus_write
  assign WILL_FIRE_RL_do_bus_write = write && state == 2'd0 ;

  // rule RL_do_idle
  assign WILL_FIRE_RL_do_idle =
	     swd_controller_state == 4'd0 && !swd_controller_status[2] &&
	     state == 2'd0 &&
	     !write &&
	     cmd[8] ;

  // rule RL_do_rw
  assign WILL_FIRE_RL_do_rw =
	     swd_controller_state == 4'd0 && swd_controller_status[2] &&
	     state == 2'd2 ;

  // inputs to muxes for submodule ports
  assign MUX_cmd$write_1__SEL_1 = state == 2'd1 && ready ;
  assign MUX_cmd$write_1__SEL_2 =
	     WILL_FIRE_RL_do_bus_write &&
	     { en_wdata_0, en_wdata_1, en_wdata_2, en_wdata_3, en_cmd } ==
	     5'b00001 ;
  assign MUX_swd_controller_cnt$write_1__PSEL_1 =
	     swd_controller_state == 4'd7 || swd_controller_state == 4'd1 ||
	     swd_controller_state == 4'd8 ;
  assign MUX_swd_controller_cnt$write_1__SEL_1 =
	     MUX_swd_controller_cnt$write_1__PSEL_1 &&
	     swd_controller_prescaler_ctr$Q_OUT == 6'd0 ;
  assign MUX_swd_controller_cnt$write_1__SEL_2 =
	     swd_controller_state == 4'd4 &&
	     swd_controller_prescaler_ctr$Q_OUT == 6'd1 ;
  assign MUX_swd_controller_cnt$write_1__SEL_3 =
	     swd_controller_state == 4'd2 &&
	     swd_controller_prescaler_ctr$Q_OUT == 6'd1 ;
  assign MUX_swd_controller_cnt$write_1__SEL_4 =
	     swd_controller_state == 4'd0 &&
	     (MUX_swd_controller_packet$write_1__SEL_2 ||
	      swd_controller_reset_in$whas) ;
  assign MUX_swd_controller_cnt$write_1__SEL_5 =
	     swd_controller_state == 4'd3 &&
	     (swd_controller_prescaler_ctr$Q_OUT == 6'd0 ||
	      swd_controller_prescaler_ctr$Q_OUT == 6'd1 &&
	      swd_controller_cnt == 7'd0 &&
	      swd_controller_rnw) ;
  assign MUX_swd_controller_cnt$write_1__PSEL_6 =
	     swd_controller_state == 4'd6 || swd_controller_state == 4'd5 ;
  assign MUX_swd_controller_cnt$write_1__SEL_6 =
	     MUX_swd_controller_cnt$write_1__PSEL_6 &&
	     (swd_controller_prescaler_ctr$Q_OUT == 6'd0 ||
	      swd_controller_prescaler_ctr$Q_OUT == 6'd1 &&
	      swd_controller_cnt == 7'd0) ;
  assign MUX_swd_controller_data$write_1__SEL_1 =
	     swd_controller_state == 4'd6 &&
	     swd_controller_prescaler_ctr$Q_OUT == 6'd0 ;
  assign MUX_swd_controller_data$write_1__SEL_2 =
	     swd_controller_state == 4'd5 &&
	     swd_controller_prescaler_ctr$Q_OUT == 6'd16 ;
  assign MUX_swd_controller_data$write_1__SEL_3 =
	     WILL_FIRE_RL_do_idle && !cmd[7] && !cmd[5] ;
  assign MUX_swd_controller_packet$write_1__SEL_1 =
	     swd_controller_state == 4'd1 &&
	     swd_controller_prescaler_ctr$Q_OUT == 6'd0 ;
  assign MUX_swd_controller_packet$write_1__SEL_2 =
	     WILL_FIRE_RL_do_idle && !cmd[7] ;
  assign MUX_swd_controller_state$write_1__SEL_3 =
	     swd_controller_state == 4'd3 &&
	     swd_controller_prescaler_ctr$Q_OUT == 6'd1 &&
	     swd_controller_cnt == 7'd0 ;
  assign MUX_swd_controller_state$write_1__PSEL_4 =
	     swd_controller_state == 4'd7 || swd_controller_state == 4'd8 ;
  assign MUX_swd_controller_state$write_1__SEL_4 =
	     MUX_swd_controller_state$write_1__PSEL_4 &&
	     swd_controller_prescaler_ctr$Q_OUT == 6'd1 &&
	     swd_controller_cnt == 7'd0 ;
  assign MUX_swd_controller_state$write_1__SEL_5 =
	     swd_controller_state == 4'd1 &&
	     swd_controller_prescaler_ctr$Q_OUT == 6'd1 &&
	     swd_controller_cnt == 7'd0 ;
  assign MUX_swd_controller_state$write_1__SEL_6 =
	     MUX_swd_controller_cnt$write_1__PSEL_6 &&
	     swd_controller_prescaler_ctr$Q_OUT == 6'd1 &&
	     swd_controller_cnt == 7'd0 ;
  assign MUX_swd_controller_status$write_1__SEL_1 =
	     swd_controller_state == 4'd7 &&
	     swd_controller_prescaler_ctr$Q_OUT == 6'd0 ;
  assign MUX_swd_controller_swclk$write_1__SEL_1 =
	     swd_controller_state != 4'd0 &&
	     (swd_controller_prescaler_ctr$Q_OUT == 6'd0 ||
	      swd_controller_prescaler_ctr$Q_OUT == 6'd16) ;
  assign MUX_swd_controller_swclk$write_1__SEL_2 =
	     swd_controller_state == 4'd0 &&
	     !MUX_swd_controller_packet$write_1__SEL_2 &&
	     !swd_controller_reset_in$whas ;
  assign MUX_swd_controller_swd_out$write_1__SEL_3 =
	     swd_controller_state == 4'd8 &&
	     swd_controller_prescaler_ctr$Q_OUT == 6'd0 ;
  assign MUX_swd_controller_swd_out$write_1__PSEL_4 =
	     swd_controller_state == 4'd4 || swd_controller_state == 4'd2 ;
  assign MUX_swd_controller_swd_out$write_1__SEL_4 =
	     MUX_swd_controller_swd_out$write_1__PSEL_4 &&
	     swd_controller_prescaler_ctr$Q_OUT == 6'd0 ;
  assign MUX_cmd$write_1__VAL_2 = { 1'd1, write_data } ;
  assign MUX_state$write_1__VAL_2 = cmd[7] ? 2'd1 : 2'd2 ;
  assign MUX_status$write_1__VAL_2 =
	     swd_controller_rnw ?
	       (swd_controller_data_9_BIT_0_3_XOR_swd_controll_ETC___d331 ?
		  2'd3 :
		  swd_controller_status[1:0]) :
	       swd_controller_status[1:0] ;
  assign MUX_swd_controller_cnt$write_1__VAL_2 =
	     (swd_controller_ack == 3'b100) ? 7'd33 : 7'd1 ;
  assign MUX_swd_controller_cnt$write_1__VAL_4 =
	     MUX_swd_controller_packet$write_1__SEL_2 ? 7'd8 : 7'd118 ;
  assign MUX_swd_controller_cnt$write_1__VAL_5 =
	     (swd_controller_prescaler_ctr$Q_OUT == 6'd0) ?
	       x__h14830 :
	       7'd33 ;
  assign MUX_swd_controller_cnt$write_1__VAL_6 =
	     (swd_controller_prescaler_ctr$Q_OUT == 6'd0) ? x__h14830 : 7'd1 ;
  assign MUX_swd_controller_data$write_1__VAL_1 =
	     { 1'd0, swd_controller_data[32:1] } ;
  assign MUX_swd_controller_data$write_1__VAL_2 =
	     { swd_controller_data[31:0], swd_in } ;
  assign MUX_swd_controller_data$write_1__VAL_3 =
	     { z__h24247 ^ wdata[31], wdata } ;
  assign MUX_swd_controller_packet$write_1__VAL_1 =
	     { 1'd0, swd_controller_packet[7:1] } ;
  assign MUX_swd_controller_packet$write_1__VAL_2 =
	     { 1'd1, cmd[6:3], x__h20797, 2'd1 } ;
  assign MUX_swd_controller_state$write_1__VAL_1 =
	     (swd_controller_ack == 3'b100) ? 4'd6 : 4'd7 ;
  assign MUX_swd_controller_state$write_1__VAL_3 =
	     swd_controller_rnw ? 4'd5 : 4'd4 ;
  assign MUX_swd_controller_state$write_1__VAL_7 =
	     MUX_swd_controller_packet$write_1__SEL_2 ? 4'd1 : 4'd8 ;
  always@(swd_controller_ack)
  begin
    case (swd_controller_ack)
      3'b001: MUX_swd_controller_status$write_1__VAL_1 = 3'd6;
      3'b010: MUX_swd_controller_status$write_1__VAL_1 = 3'd5;
      3'b100: MUX_swd_controller_status$write_1__VAL_1 = swd_controller_ack;
      default: MUX_swd_controller_status$write_1__VAL_1 = 3'd7;
    endcase
  end
  assign MUX_swd_controller_swd_out$write_1__VAL_3 =
	     swd_controller_cnt > 7'd67 || swd_controller_cnt <= 7'd51 ||
	     x__h1333 ;

  // inlined wires
  assign swd_controller_reset_in$whas = WILL_FIRE_RL_do_idle && cmd[7] ;

  // register bus_reg_rdata_0
  assign bus_reg_rdata_0$D_IN = rdata[7:0] ;
  assign bus_reg_rdata_0$EN =
	     read &&
	     { en_rdata_0, en_rdata_1, en_rdata_2, en_rdata_3, en_status } ==
	     5'b10000 ;

  // register bus_reg_rdata_1
  assign bus_reg_rdata_1$D_IN = rdata[15:8] ;
  assign bus_reg_rdata_1$EN =
	     read &&
	     { en_rdata_0, en_rdata_1, en_rdata_2, en_rdata_3, en_status } ==
	     5'b01000 ;

  // register bus_reg_rdata_2
  assign bus_reg_rdata_2$D_IN = rdata[23:16] ;
  assign bus_reg_rdata_2$EN =
	     read &&
	     { en_rdata_0, en_rdata_1, en_rdata_2, en_rdata_3, en_status } ==
	     5'b00100 ;

  // register bus_reg_rdata_3
  assign bus_reg_rdata_3$D_IN = rdata[31:24] ;
  assign bus_reg_rdata_3$EN =
	     read &&
	     { en_rdata_0, en_rdata_1, en_rdata_2, en_rdata_3, en_status } ==
	     5'b00010 ;

  // register bus_reg_status
  assign bus_reg_status$D_IN = { state == 2'd0, 5'b0, status } ;
  assign bus_reg_status$EN =
	     read &&
	     { en_rdata_0, en_rdata_1, en_rdata_2, en_rdata_3, en_status } ==
	     5'b00001 ;

  // register cmd
  assign cmd$D_IN = MUX_cmd$write_1__SEL_2 ? MUX_cmd$write_1__VAL_2 : 9'd170 ;
  assign cmd$EN =
	     state == 2'd1 && ready || MUX_cmd$write_1__SEL_2 ||
	     WILL_FIRE_RL_do_rw ;

  // register rdata
  assign rdata$D_IN =
	     swd_controller_rnw ?
	       (swd_controller_data_9_BIT_0_3_XOR_swd_controll_ETC___d331 ?
		  32'd0 :
		  swd_controller_data[31:0]) :
	       32'd0 ;
  assign rdata$EN = WILL_FIRE_RL_do_rw ;

  // register ready
  assign ready$D_IN = swd_controller_state == 4'd0 ;
  assign ready$EN = 1'd1 ;

  // register state
  assign state$D_IN = WILL_FIRE_RL_do_idle ? MUX_state$write_1__VAL_2 : 2'd0 ;
  assign state$EN =
	     state == 2'd1 && ready || WILL_FIRE_RL_do_idle ||
	     WILL_FIRE_RL_do_rw ;

  // register status
  assign status$D_IN =
	     MUX_cmd$write_1__SEL_1 ? 2'd0 : MUX_status$write_1__VAL_2 ;
  assign status$EN = state == 2'd1 && ready || WILL_FIRE_RL_do_rw ;

  // register swd_controller_ack
  assign swd_controller_ack$D_IN = { swd_controller_ack[1:0], swd_in } ;
  assign swd_controller_ack$EN =
	     swd_controller_state == 4'd3 &&
	     swd_controller_prescaler_ctr$Q_OUT == 6'd16 ;

  // register swd_controller_cnt
  always@(MUX_swd_controller_cnt$write_1__SEL_1 or
	  x__h14830 or
	  MUX_swd_controller_cnt$write_1__SEL_2 or
	  MUX_swd_controller_cnt$write_1__VAL_2 or
	  MUX_swd_controller_cnt$write_1__SEL_3 or
	  MUX_swd_controller_cnt$write_1__SEL_4 or
	  MUX_swd_controller_cnt$write_1__VAL_4 or
	  MUX_swd_controller_cnt$write_1__SEL_5 or
	  MUX_swd_controller_cnt$write_1__VAL_5 or
	  MUX_swd_controller_cnt$write_1__SEL_6 or
	  MUX_swd_controller_cnt$write_1__VAL_6)
  begin
    case (1'b1) // synopsys parallel_case
      MUX_swd_controller_cnt$write_1__SEL_1:
	  swd_controller_cnt$D_IN = x__h14830;
      MUX_swd_controller_cnt$write_1__SEL_2:
	  swd_controller_cnt$D_IN = MUX_swd_controller_cnt$write_1__VAL_2;
      MUX_swd_controller_cnt$write_1__SEL_3: swd_controller_cnt$D_IN = 7'd3;
      MUX_swd_controller_cnt$write_1__SEL_4:
	  swd_controller_cnt$D_IN = MUX_swd_controller_cnt$write_1__VAL_4;
      MUX_swd_controller_cnt$write_1__SEL_5:
	  swd_controller_cnt$D_IN = MUX_swd_controller_cnt$write_1__VAL_5;
      MUX_swd_controller_cnt$write_1__SEL_6:
	  swd_controller_cnt$D_IN = MUX_swd_controller_cnt$write_1__VAL_6;
      default: swd_controller_cnt$D_IN = 7'b0101010 /* unspecified value */ ;
    endcase
  end
  assign swd_controller_cnt$EN =
	     (swd_controller_state == 4'd7 || swd_controller_state == 4'd1 ||
	      swd_controller_state == 4'd8) &&
	     swd_controller_prescaler_ctr$Q_OUT == 6'd0 ||
	     swd_controller_state == 4'd4 &&
	     swd_controller_prescaler_ctr$Q_OUT == 6'd1 ||
	     swd_controller_state == 4'd2 &&
	     swd_controller_prescaler_ctr$Q_OUT == 6'd1 ||
	     swd_controller_state == 4'd0 &&
	     (MUX_swd_controller_packet$write_1__SEL_2 ||
	      swd_controller_reset_in$whas) ||
	     MUX_swd_controller_cnt$write_1__SEL_5 ||
	     (swd_controller_state == 4'd6 || swd_controller_state == 4'd5) &&
	     (swd_controller_prescaler_ctr$Q_OUT == 6'd0 ||
	      swd_controller_prescaler_ctr$Q_OUT == 6'd1 &&
	      swd_controller_cnt == 7'd0) ;

  // register swd_controller_data
  always@(MUX_swd_controller_data$write_1__SEL_1 or
	  MUX_swd_controller_data$write_1__VAL_1 or
	  MUX_swd_controller_data$write_1__SEL_2 or
	  MUX_swd_controller_data$write_1__VAL_2 or
	  MUX_swd_controller_data$write_1__SEL_3 or
	  MUX_swd_controller_data$write_1__VAL_3 or WILL_FIRE_RL_do_rw)
  begin
    case (1'b1) // synopsys parallel_case
      MUX_swd_controller_data$write_1__SEL_1:
	  swd_controller_data$D_IN = MUX_swd_controller_data$write_1__VAL_1;
      MUX_swd_controller_data$write_1__SEL_2:
	  swd_controller_data$D_IN = MUX_swd_controller_data$write_1__VAL_2;
      MUX_swd_controller_data$write_1__SEL_3:
	  swd_controller_data$D_IN = MUX_swd_controller_data$write_1__VAL_3;
      WILL_FIRE_RL_do_rw: swd_controller_data$D_IN = 33'd0;
      default: swd_controller_data$D_IN =
		   33'h0AAAAAAAA /* unspecified value */ ;
    endcase
  end
  assign swd_controller_data$EN =
	     swd_controller_state == 4'd6 &&
	     swd_controller_prescaler_ctr$Q_OUT == 6'd0 ||
	     swd_controller_state == 4'd5 &&
	     swd_controller_prescaler_ctr$Q_OUT == 6'd16 ||
	     WILL_FIRE_RL_do_idle && !cmd[7] && !cmd[5] ||
	     WILL_FIRE_RL_do_rw ;

  // register swd_controller_out_en
  assign swd_controller_out_en$D_IN =
	     swd_controller_state != 4'd3 && swd_controller_state != 4'd5 ;
  assign swd_controller_out_en$EN = 1'd1 ;

  // register swd_controller_packet
  always@(MUX_swd_controller_packet$write_1__SEL_1 or
	  MUX_swd_controller_packet$write_1__VAL_1 or
	  MUX_swd_controller_packet$write_1__SEL_2 or
	  MUX_swd_controller_packet$write_1__VAL_2 or WILL_FIRE_RL_do_rw)
  begin
    case (1'b1) // synopsys parallel_case
      MUX_swd_controller_packet$write_1__SEL_1:
	  swd_controller_packet$D_IN =
	      MUX_swd_controller_packet$write_1__VAL_1;
      MUX_swd_controller_packet$write_1__SEL_2:
	  swd_controller_packet$D_IN =
	      MUX_swd_controller_packet$write_1__VAL_2;
      WILL_FIRE_RL_do_rw: swd_controller_packet$D_IN = 8'd0;
      default: swd_controller_packet$D_IN =
		   8'b10101010 /* unspecified value */ ;
    endcase
  end
  assign swd_controller_packet$EN =
	     swd_controller_state == 4'd1 &&
	     swd_controller_prescaler_ctr$Q_OUT == 6'd0 ||
	     WILL_FIRE_RL_do_idle && !cmd[7] ||
	     WILL_FIRE_RL_do_rw ;

  // register swd_controller_rnw
  assign swd_controller_rnw$D_IN = cmd[5] ;
  assign swd_controller_rnw$EN = MUX_swd_controller_packet$write_1__SEL_2 ;

  // register swd_controller_state
  always@(MUX_swd_controller_cnt$write_1__SEL_2 or
	  MUX_swd_controller_state$write_1__VAL_1 or
	  MUX_swd_controller_cnt$write_1__SEL_3 or
	  MUX_swd_controller_state$write_1__SEL_3 or
	  MUX_swd_controller_state$write_1__VAL_3 or
	  MUX_swd_controller_state$write_1__SEL_4 or
	  MUX_swd_controller_state$write_1__SEL_5 or
	  MUX_swd_controller_state$write_1__SEL_6 or
	  MUX_swd_controller_cnt$write_1__SEL_4 or
	  MUX_swd_controller_state$write_1__VAL_7)
  begin
    case (1'b1) // synopsys parallel_case
      MUX_swd_controller_cnt$write_1__SEL_2:
	  swd_controller_state$D_IN = MUX_swd_controller_state$write_1__VAL_1;
      MUX_swd_controller_cnt$write_1__SEL_3: swd_controller_state$D_IN = 4'd3;
      MUX_swd_controller_state$write_1__SEL_3:
	  swd_controller_state$D_IN = MUX_swd_controller_state$write_1__VAL_3;
      MUX_swd_controller_state$write_1__SEL_4:
	  swd_controller_state$D_IN = 4'd0;
      MUX_swd_controller_state$write_1__SEL_5:
	  swd_controller_state$D_IN = 4'd2;
      MUX_swd_controller_state$write_1__SEL_6:
	  swd_controller_state$D_IN = 4'd7;
      MUX_swd_controller_cnt$write_1__SEL_4:
	  swd_controller_state$D_IN = MUX_swd_controller_state$write_1__VAL_7;
      default: swd_controller_state$D_IN = 4'b1010 /* unspecified value */ ;
    endcase
  end
  assign swd_controller_state$EN =
	     swd_controller_state == 4'd4 &&
	     swd_controller_prescaler_ctr$Q_OUT == 6'd1 ||
	     swd_controller_state == 4'd2 &&
	     swd_controller_prescaler_ctr$Q_OUT == 6'd1 ||
	     swd_controller_state == 4'd3 &&
	     swd_controller_prescaler_ctr$Q_OUT == 6'd1 &&
	     swd_controller_cnt == 7'd0 ||
	     (swd_controller_state == 4'd7 || swd_controller_state == 4'd8) &&
	     swd_controller_prescaler_ctr$Q_OUT == 6'd1 &&
	     swd_controller_cnt == 7'd0 ||
	     swd_controller_state == 4'd1 &&
	     swd_controller_prescaler_ctr$Q_OUT == 6'd1 &&
	     swd_controller_cnt == 7'd0 ||
	     (swd_controller_state == 4'd6 || swd_controller_state == 4'd5) &&
	     swd_controller_prescaler_ctr$Q_OUT == 6'd1 &&
	     swd_controller_cnt == 7'd0 ||
	     swd_controller_state == 4'd0 &&
	     (MUX_swd_controller_packet$write_1__SEL_2 ||
	      swd_controller_reset_in$whas) ;

  // register swd_controller_status
  assign swd_controller_status$D_IN =
	     MUX_swd_controller_status$write_1__SEL_1 ?
	       MUX_swd_controller_status$write_1__VAL_1 :
	       3'd2 ;
  assign swd_controller_status$EN =
	     swd_controller_state == 4'd7 &&
	     swd_controller_prescaler_ctr$Q_OUT == 6'd0 ||
	     WILL_FIRE_RL_do_rw ;

  // register swd_controller_swclk
  assign swd_controller_swclk$D_IN =
	     MUX_swd_controller_swclk$write_1__SEL_1 &&
	     swd_controller_prescaler_ctr$Q_OUT == 6'd0 ;
  assign swd_controller_swclk$EN =
	     swd_controller_state != 4'd0 &&
	     (swd_controller_prescaler_ctr$Q_OUT == 6'd0 ||
	      swd_controller_prescaler_ctr$Q_OUT == 6'd16) ||
	     swd_controller_state == 4'd0 &&
	     !MUX_swd_controller_packet$write_1__SEL_2 &&
	     !swd_controller_reset_in$whas ;

  // register swd_controller_swd_out
  always@(MUX_swd_controller_packet$write_1__SEL_1 or
	  swd_controller_packet or
	  MUX_swd_controller_data$write_1__SEL_1 or
	  swd_controller_data or
	  MUX_swd_controller_swd_out$write_1__SEL_3 or
	  MUX_swd_controller_swd_out$write_1__VAL_3 or
	  MUX_swd_controller_swd_out$write_1__SEL_4 or
	  MUX_swd_controller_swclk$write_1__SEL_2)
  begin
    case (1'b1) // synopsys parallel_case
      MUX_swd_controller_packet$write_1__SEL_1:
	  swd_controller_swd_out$D_IN = swd_controller_packet[0];
      MUX_swd_controller_data$write_1__SEL_1:
	  swd_controller_swd_out$D_IN = swd_controller_data[0];
      MUX_swd_controller_swd_out$write_1__SEL_3:
	  swd_controller_swd_out$D_IN =
	      MUX_swd_controller_swd_out$write_1__VAL_3;
      MUX_swd_controller_swd_out$write_1__SEL_4 ||
      MUX_swd_controller_swclk$write_1__SEL_2:
	  swd_controller_swd_out$D_IN = 1'd0;
      default: swd_controller_swd_out$D_IN = 1'b0 /* unspecified value */ ;
    endcase
  end
  assign swd_controller_swd_out$EN =
	     swd_controller_state == 4'd1 &&
	     swd_controller_prescaler_ctr$Q_OUT == 6'd0 ||
	     swd_controller_state == 4'd6 &&
	     swd_controller_prescaler_ctr$Q_OUT == 6'd0 ||
	     swd_controller_state == 4'd8 &&
	     swd_controller_prescaler_ctr$Q_OUT == 6'd0 ||
	     (swd_controller_state == 4'd4 || swd_controller_state == 4'd2) &&
	     swd_controller_prescaler_ctr$Q_OUT == 6'd0 ||
	     swd_controller_state == 4'd0 &&
	     !MUX_swd_controller_packet$write_1__SEL_2 &&
	     !swd_controller_reset_in$whas ;

  // register wdata
  always@(en_wdata_0 or
	  en_wdata_1 or
	  en_wdata_2 or en_wdata_3 or en_cmd or write_data or wdata)
  begin
    case ({ en_wdata_0, en_wdata_1, en_wdata_2, en_wdata_3, en_cmd })
      5'b00100: wdata$D_IN = { wdata[31:24], write_data, wdata[15:0] };
      5'b01000: wdata$D_IN = { wdata[31:16], write_data, wdata[7:0] };
      5'b10000: wdata$D_IN = { wdata[31:8], write_data };
      default: wdata$D_IN = { write_data, wdata[23:0] };
    endcase
  end
  assign wdata$EN =
	     WILL_FIRE_RL_do_bus_write &&
	     bus_en_wdata_0_whas__25_AND_bus_en_wdata_0_wge_ETC___d148 ;

  // submodule swd_controller_prescaler_ctr
  assign swd_controller_prescaler_ctr$DATA_A = 6'h0 ;
  assign swd_controller_prescaler_ctr$DATA_B = 6'd63 ;
  assign swd_controller_prescaler_ctr$DATA_C = 6'h0 ;
  assign swd_controller_prescaler_ctr$DATA_F = 6'd31 ;
  assign swd_controller_prescaler_ctr$ADDA = 1'b0 ;
  assign swd_controller_prescaler_ctr$ADDB =
	     swd_controller_prescaler_ctr$Q_OUT != 6'd0 ;
  assign swd_controller_prescaler_ctr$SETC = 1'b0 ;
  assign swd_controller_prescaler_ctr$SETF =
	     swd_controller_prescaler_ctr$Q_OUT == 6'd0 ;

  // remaining internal signals
  assign _0xE79E__q2 = 16'hE79E ;
  assign bus_en_wdata_0_whas__25_AND_bus_en_wdata_0_wge_ETC___d146 =
	     { en_wdata_0, en_wdata_1, en_wdata_2, en_wdata_3, en_cmd } ==
	     5'b00100 ||
	     { en_wdata_0, en_wdata_1, en_wdata_2, en_wdata_3, en_cmd } ==
	     5'b00010 ;
  assign bus_en_wdata_0_whas__25_AND_bus_en_wdata_0_wge_ETC___d147 =
	     { en_wdata_0, en_wdata_1, en_wdata_2, en_wdata_3, en_cmd } ==
	     5'b01000 ||
	     bus_en_wdata_0_whas__25_AND_bus_en_wdata_0_wge_ETC___d146 ;
  assign bus_en_wdata_0_whas__25_AND_bus_en_wdata_0_wge_ETC___d148 =
	     { en_wdata_0, en_wdata_1, en_wdata_2, en_wdata_3, en_cmd } ==
	     5'b10000 ||
	     bus_en_wdata_0_whas__25_AND_bus_en_wdata_0_wge_ETC___d147 ;
  assign cmd_BITS_4_TO_3__q1 = cmd[4:3] ;
  assign i__h1352 = 7'd67 - swd_controller_cnt ;
  assign swd_controller_data_9_BIT_0_3_XOR_swd_controll_ETC___d331 =
	     z__h34759 ^ swd_controller_data[32] ;
  assign x__h1333 = _0xE79E__q2[i__h1352[3:0]] ;
  assign x__h14830 = swd_controller_cnt - 7'd1 ;
  assign x__h20797 = x__h20810 ^ cmd_BITS_4_TO_3__q1[1] ;
  assign x__h20810 = cmd[6] ^ cmd_BITS_4_TO_3__q1[0] ;
  assign z__h24044 = wdata[0] ^ wdata[1] ;
  assign z__h24051 = z__h24044 ^ wdata[2] ;
  assign z__h24058 = z__h24051 ^ wdata[3] ;
  assign z__h24065 = z__h24058 ^ wdata[4] ;
  assign z__h24072 = z__h24065 ^ wdata[5] ;
  assign z__h24079 = z__h24072 ^ wdata[6] ;
  assign z__h24086 = z__h24079 ^ wdata[7] ;
  assign z__h24093 = z__h24086 ^ wdata[8] ;
  assign z__h24100 = z__h24093 ^ wdata[9] ;
  assign z__h24107 = z__h24100 ^ wdata[10] ;
  assign z__h24114 = z__h24107 ^ wdata[11] ;
  assign z__h24121 = z__h24114 ^ wdata[12] ;
  assign z__h24128 = z__h24121 ^ wdata[13] ;
  assign z__h24135 = z__h24128 ^ wdata[14] ;
  assign z__h24142 = z__h24135 ^ wdata[15] ;
  assign z__h24149 = z__h24142 ^ wdata[16] ;
  assign z__h24156 = z__h24149 ^ wdata[17] ;
  assign z__h24163 = z__h24156 ^ wdata[18] ;
  assign z__h24170 = z__h24163 ^ wdata[19] ;
  assign z__h24177 = z__h24170 ^ wdata[20] ;
  assign z__h24184 = z__h24177 ^ wdata[21] ;
  assign z__h24191 = z__h24184 ^ wdata[22] ;
  assign z__h24198 = z__h24191 ^ wdata[23] ;
  assign z__h24205 = z__h24198 ^ wdata[24] ;
  assign z__h24212 = z__h24205 ^ wdata[25] ;
  assign z__h24219 = z__h24212 ^ wdata[26] ;
  assign z__h24226 = z__h24219 ^ wdata[27] ;
  assign z__h24233 = z__h24226 ^ wdata[28] ;
  assign z__h24240 = z__h24233 ^ wdata[29] ;
  assign z__h24247 = z__h24240 ^ wdata[30] ;
  assign z__h34549 = swd_controller_data[0] ^ swd_controller_data[1] ;
  assign z__h34556 = z__h34549 ^ swd_controller_data[2] ;
  assign z__h34563 = z__h34556 ^ swd_controller_data[3] ;
  assign z__h34570 = z__h34563 ^ swd_controller_data[4] ;
  assign z__h34577 = z__h34570 ^ swd_controller_data[5] ;
  assign z__h34584 = z__h34577 ^ swd_controller_data[6] ;
  assign z__h34591 = z__h34584 ^ swd_controller_data[7] ;
  assign z__h34598 = z__h34591 ^ swd_controller_data[8] ;
  assign z__h34605 = z__h34598 ^ swd_controller_data[9] ;
  assign z__h34612 = z__h34605 ^ swd_controller_data[10] ;
  assign z__h34619 = z__h34612 ^ swd_controller_data[11] ;
  assign z__h34626 = z__h34619 ^ swd_controller_data[12] ;
  assign z__h34633 = z__h34626 ^ swd_controller_data[13] ;
  assign z__h34640 = z__h34633 ^ swd_controller_data[14] ;
  assign z__h34647 = z__h34640 ^ swd_controller_data[15] ;
  assign z__h34654 = z__h34647 ^ swd_controller_data[16] ;
  assign z__h34661 = z__h34654 ^ swd_controller_data[17] ;
  assign z__h34668 = z__h34661 ^ swd_controller_data[18] ;
  assign z__h34675 = z__h34668 ^ swd_controller_data[19] ;
  assign z__h34682 = z__h34675 ^ swd_controller_data[20] ;
  assign z__h34689 = z__h34682 ^ swd_controller_data[21] ;
  assign z__h34696 = z__h34689 ^ swd_controller_data[22] ;
  assign z__h34703 = z__h34696 ^ swd_controller_data[23] ;
  assign z__h34710 = z__h34703 ^ swd_controller_data[24] ;
  assign z__h34717 = z__h34710 ^ swd_controller_data[25] ;
  assign z__h34724 = z__h34717 ^ swd_controller_data[26] ;
  assign z__h34731 = z__h34724 ^ swd_controller_data[27] ;
  assign z__h34738 = z__h34731 ^ swd_controller_data[28] ;
  assign z__h34745 = z__h34738 ^ swd_controller_data[29] ;
  assign z__h34752 = z__h34745 ^ swd_controller_data[30] ;
  assign z__h34759 = z__h34752 ^ swd_controller_data[31] ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        bus_reg_rdata_0 <= `BSV_ASSIGNMENT_DELAY 8'd0;
	bus_reg_rdata_1 <= `BSV_ASSIGNMENT_DELAY 8'd0;
	bus_reg_rdata_2 <= `BSV_ASSIGNMENT_DELAY 8'd0;
	bus_reg_rdata_3 <= `BSV_ASSIGNMENT_DELAY 8'd0;
	bus_reg_status <= `BSV_ASSIGNMENT_DELAY 8'd0;
	cmd <= `BSV_ASSIGNMENT_DELAY 9'd170;
	rdata <= `BSV_ASSIGNMENT_DELAY 32'd0;
	ready <= `BSV_ASSIGNMENT_DELAY 1'd0;
	state <= `BSV_ASSIGNMENT_DELAY 2'd0;
	status <= `BSV_ASSIGNMENT_DELAY 2'd0;
	swd_controller_ack <= `BSV_ASSIGNMENT_DELAY 3'd0;
	swd_controller_out_en <= `BSV_ASSIGNMENT_DELAY 1'd1;
	swd_controller_state <= `BSV_ASSIGNMENT_DELAY 4'd0;
	swd_controller_status <= `BSV_ASSIGNMENT_DELAY 3'd2;
	swd_controller_swclk <= `BSV_ASSIGNMENT_DELAY 1'd0;
	swd_controller_swd_out <= `BSV_ASSIGNMENT_DELAY 1'd0;
	wdata <= `BSV_ASSIGNMENT_DELAY 32'd0;
      end
    else
      begin
        if (bus_reg_rdata_0$EN)
	  bus_reg_rdata_0 <= `BSV_ASSIGNMENT_DELAY bus_reg_rdata_0$D_IN;
	if (bus_reg_rdata_1$EN)
	  bus_reg_rdata_1 <= `BSV_ASSIGNMENT_DELAY bus_reg_rdata_1$D_IN;
	if (bus_reg_rdata_2$EN)
	  bus_reg_rdata_2 <= `BSV_ASSIGNMENT_DELAY bus_reg_rdata_2$D_IN;
	if (bus_reg_rdata_3$EN)
	  bus_reg_rdata_3 <= `BSV_ASSIGNMENT_DELAY bus_reg_rdata_3$D_IN;
	if (bus_reg_status$EN)
	  bus_reg_status <= `BSV_ASSIGNMENT_DELAY bus_reg_status$D_IN;
	if (cmd$EN) cmd <= `BSV_ASSIGNMENT_DELAY cmd$D_IN;
	if (rdata$EN) rdata <= `BSV_ASSIGNMENT_DELAY rdata$D_IN;
	if (ready$EN) ready <= `BSV_ASSIGNMENT_DELAY ready$D_IN;
	if (state$EN) state <= `BSV_ASSIGNMENT_DELAY state$D_IN;
	if (status$EN) status <= `BSV_ASSIGNMENT_DELAY status$D_IN;
	if (swd_controller_ack$EN)
	  swd_controller_ack <= `BSV_ASSIGNMENT_DELAY swd_controller_ack$D_IN;
	if (swd_controller_out_en$EN)
	  swd_controller_out_en <= `BSV_ASSIGNMENT_DELAY
	      swd_controller_out_en$D_IN;
	if (swd_controller_state$EN)
	  swd_controller_state <= `BSV_ASSIGNMENT_DELAY
	      swd_controller_state$D_IN;
	if (swd_controller_status$EN)
	  swd_controller_status <= `BSV_ASSIGNMENT_DELAY
	      swd_controller_status$D_IN;
	if (swd_controller_swclk$EN)
	  swd_controller_swclk <= `BSV_ASSIGNMENT_DELAY
	      swd_controller_swclk$D_IN;
	if (swd_controller_swd_out$EN)
	  swd_controller_swd_out <= `BSV_ASSIGNMENT_DELAY
	      swd_controller_swd_out$D_IN;
	if (wdata$EN) wdata <= `BSV_ASSIGNMENT_DELAY wdata$D_IN;
      end
    if (swd_controller_cnt$EN)
      swd_controller_cnt <= `BSV_ASSIGNMENT_DELAY swd_controller_cnt$D_IN;
    if (swd_controller_data$EN)
      swd_controller_data <= `BSV_ASSIGNMENT_DELAY swd_controller_data$D_IN;
    if (swd_controller_packet$EN)
      swd_controller_packet <= `BSV_ASSIGNMENT_DELAY
	  swd_controller_packet$D_IN;
    if (swd_controller_rnw$EN)
      swd_controller_rnw <= `BSV_ASSIGNMENT_DELAY swd_controller_rnw$D_IN;
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    bus_reg_rdata_0 = 8'hAA;
    bus_reg_rdata_1 = 8'hAA;
    bus_reg_rdata_2 = 8'hAA;
    bus_reg_rdata_3 = 8'hAA;
    bus_reg_status = 8'hAA;
    cmd = 9'h0AA;
    rdata = 32'hAAAAAAAA;
    ready = 1'h0;
    state = 2'h2;
    status = 2'h2;
    swd_controller_ack = 3'h2;
    swd_controller_cnt = 7'h2A;
    swd_controller_data = 33'h0AAAAAAAA;
    swd_controller_out_en = 1'h0;
    swd_controller_packet = 8'hAA;
    swd_controller_rnw = 1'h0;
    swd_controller_state = 4'hA;
    swd_controller_status = 3'h2;
    swd_controller_swclk = 1'h0;
    swd_controller_swd_out = 1'h0;
    wdata = 32'hAAAAAAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE) $write("state: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (swd_controller_state == 4'd0) $write("IDLE");
    if (RST_N != `BSV_RESET_VALUE)
      if (swd_controller_state == 4'd1) $write("PACKET");
    if (RST_N != `BSV_RESET_VALUE)
      if (swd_controller_state == 4'd2) $write("P_TRN");
    if (RST_N != `BSV_RESET_VALUE)
      if (swd_controller_state == 4'd3) $write("ACK");
    if (RST_N != `BSV_RESET_VALUE)
      if (swd_controller_state == 4'd4) $write("A_TRN");
    if (RST_N != `BSV_RESET_VALUE)
      if (swd_controller_state == 4'd5) $write("RDATA");
    if (RST_N != `BSV_RESET_VALUE)
      if (swd_controller_state == 4'd6) $write("WDATA");
    if (RST_N != `BSV_RESET_VALUE)
      if (swd_controller_state == 4'd7) $write("DONE");
    if (RST_N != `BSV_RESET_VALUE)
      if (swd_controller_state != 4'd0 && swd_controller_state != 4'd1 &&
	  swd_controller_state != 4'd2 &&
	  swd_controller_state != 4'd3 &&
	  swd_controller_state != 4'd4 &&
	  swd_controller_state != 4'd5 &&
	  swd_controller_state != 4'd6 &&
	  swd_controller_state != 4'd7)
	$write("RESET");
    if (RST_N != `BSV_RESET_VALUE)
      $write(", swclk: %b, swd_out: %b, swd_in: %b, out_en: %b",
	     swd_controller_swclk,
	     swd_controller_swd_out,
	     swd_in,
	     swd_controller_out_en,
	     "\n");
  end
  // synopsys translate_on
endmodule  // swd_module

