name: Continuous Integration

# Controls when the workflow will run
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Update apt packages
        run: sudo apt update
      - name: Install apt packages
        run: sudo apt install pcsc-tools
      - name: Install pip packages
        run: pip install flake8 pytest crcmod pycrypto
      - name: Lint Python
        run: find . -type f -name '*.py' -exec flake8 '{}' '+'
      - name: Test Python
        run: python3 -m pytest
        working-directory: api
